HEADER = C:\Users\Administrator\AppData\Local\Programs\Python\Python311\include
LIBRARY = C:\Users\Administrator\AppData\Local\Programs\Python\Python311

all:
	#g++ .\debugger.cpp -o .\debugger -g
	g++ .\debugger.cpp -o debugger -g -I$(HEADER) -L$(LIBRARY) -lpython311
